---
title: "EDA"
output: 
    pdf_document
---

```{r include=FALSE, echo=FALSE}
library(tidyverse)
library(data.table)
library(maps)
library(ggplot2)
```


```{r}
origin_df <- read.csv("hurrican703.csv")

# identify a problem in the data wrangling part far below:
# different hurricanes with same names.
# for visualization, we need to fix the problem first.
dt <- 
  origin_df %>% 
  mutate(
    # 2 hurricanes with the name ALICE.1954
    ID = ifelse(ID == "ALICE.1954" & Month == "June", "ALICE.1954(1)", ID),
    ID = ifelse(ID == "ALICE.1954", "ALICE.1954(2)", ID),
    # 4 hurricanes with the name SUBTROP:UNNAMED.1974
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "June", "SUBTROP:UNNAMED.1974(1)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "July", "SUBTROP:UNNAMED.1974(2)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "August", "SUBTROP:UNNAMED.1974(3)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974", "SUBTROP:UNNAMED.1974(4)", ID),
    # 2 hurricanes with the name SUBTROP:UNNAMED.1976
    ID = ifelse(ID == "SUBTROP:UNNAMED.1976" & Month == "May", "SUBTROP:UNNAMED.1976(1)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1976", "SUBTROP:UNNAMED.1976(2)", ID)
  )
```

### Given code for visualization

```{r}
ggplot(data=dt, aes(x = Longitude, y = Latitude)) + 
  stat_summary_2d(data = dt, aes(x = Longitude, y = Latitude, z = Wind.kt), fun = median, binwidth = c(1, 1), show.legend = TRUE)
dt <- as.data.table(dt)
summary(dt)
```

```{r}
map <- ggplot(data = dt, aes(x = Longitude, y = Latitude)) + 
  geom_polygon(data = map_data(map = 'world'), aes(x = long, y = lat, group = group))
map +
  stat_summary_2d(data = dt, aes(x = Longitude, y = Latitude, z = dt$Wind.kt), fun = median, binwidth = c(1, 1), show.legend = TRUE, alpha = 0.75) + 
  ggtitle(paste0("Atlantic Windstorm mean knot"))
```

```{r}
map <- ggplot(dt, aes(x = Longitude, y = Latitude, group = ID)) + 
  geom_polygon(data = map_data("world"), 
               aes(x = long, y = lat, group = group), 
               fill = "gray25", colour = "gray10", size = 0.2) + 
  geom_path(data = dt, aes(group = ID, colour = Wind.kt), size = 0.5) + 
  xlim(-138, -20) + ylim(3, 55) + 
  labs(x = "", y = "", colour = "Wind \n(knots)") + 
  theme(panel.background = element_rect(fill = "gray10", colour = "gray30"),
        axis.text.x = element_blank(), axis.text.y = element_blank(), 
        axis.ticks = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

seasonrange <- paste(range(dt[, Season]), collapse=" - ")

map + ggtitle(paste("Atlantic named Windstorm Trajectories (", 
                     seasonrange, ")\n")) 
```

```{r}
mapMonth <- map + facet_wrap(~ Month) +
  ggtitle(paste("Atlantic named Windstorm Trajectories by Month (", 
                 seasonrange, ")\n")) 
mapMonth
```

### EDA 
```{r}
dt_long <- dt %>%
    dplyr::group_by(ID) %>% 
    mutate(Wind_prev = lag(Wind.kt, 1),
           Lat_change = Latitude - lag(Latitude, 1),
           Long_change = Longitude - lag(Longitude, 1),
           Wind_prev_prev = lag(Wind.kt, 2)) %>% 
    mutate(Wind_change = Wind_prev - Wind_prev_prev) %>% 
  drop_na()
```


### Count of hurricanes in each month
```{r}
storms_month_name <-distinct(group_by(select(dt_long, Month, ID), Month))

storms_month_name %>% 
  dplyr::group_by(Month) %>% 
  mutate(Month =  factor(Month, levels = month.name)) %>%  
  ggplot(aes(x = Month)) +
  geom_bar()+
  labs(
    x = "Month",
    y = "Hurricanes count"
  )
```

### Average Speed (knot) of Hurricanes in Each Month

```{r }
dt_long %>% 
  ggplot(aes(x=Month,y=Wind.kt,group=Month,color=Month))+
  geom_boxplot()+
  labs(y="Wind speed")


dt_long %>% 
  dplyr::group_by(Month) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Month, avg_speed) %>% 
  mutate(Month =  factor(Month, levels = month.name))%>% 
  ggplot(aes(x = Month, y = avg_speed)) +
  geom_point()+
  scale_y_continuous("Average Speed (knot)")
```

### - Count of Hurricanes in Each Year

```{r }
storms_season_name = distinct(group_by(select(dt_long, Season, ID), Season))
ggplot(data = storms_season_name) + 
  geom_bar(aes(x = Season)) +
  scale_x_continuous("Year")+
  labs(x="Hurricanes count")
```

### average speed in each year

```{r}
dt_long %>% 
  dplyr::group_by(Season) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Season, avg_speed) %>% 
  ggplot(aes(x = Season, y = avg_speed)) +
  geom_point() +
  geom_smooth(method = "loess") +
  scale_y_continuous("Average Speed (knot)") +
  scale_x_continuous("Year") 
```

### Hurricanes count in each nature
```{r}
dt_long %>% select(Nature,ID) %>% 
  group_by(Nature) %>% 
  summarize(n_obs = n()) %>%
  mutate(Nature = fct_reorder(Nature,n_obs)) %>%
  ggplot(aes(x = Nature,y = n_obs,fill=Nature)) + 
  geom_bar(stat = "identity") +
  labs(x = "Nature", y = "Hurricanes count")
```
### Wind speed density in each nature
```{r}
dt_long %>% 
  ggplot(aes(x=Wind.kt,group=Nature,color=Nature))+
  geom_density()
```

### Wind speed boxplot in Nature
```{r}
dt_long %>% 
  ggplot(aes(x=Nature,y=Wind.kt,group=Nature,color=Nature))+
  geom_boxplot()+
  labs(y="Wind speed")


dt_long %>% 
  dplyr::group_by(Nature) %>% 
  mutate(avg_speed = mean(Wind.kt)) %>% 
  distinct(Nature, avg_speed) %>% 
  ggplot(aes(x = Nature, y = avg_speed)) +
  geom_point() +
  scale_y_continuous("Average Speed (knot)") 
# + ggtitle("Average Speed (knot) of Hurricanes in Each Nature")
```










### Data wrangling

```{r}
hurricane_df <- origin_df %>% 
  mutate(
    Month = as.factor(Month), # April-January
    Nature = as.factor(Nature), # TS,ET,DS,SS,NR
    # note: one hurricane can have multiple natures throughout its life
    time = gsub("[()]", "", time),
    time = paste0(ifelse(substr(time, 1, 2) > 23, "19", "20"), time),
    time = as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S"),
    hour = substr(time, 12, 19)
  ) %>% 
  # remove data not at six-hour time intervals. (613 observations)
  filter(hour %in% c("00:00:00", "06:00:00", "12:00:00", "18:00:00")) %>% 
  select(-hour)

# remove hurricanes that has only 2 (<3) observations (change the threshold if you wish)
few_id <- hurricane_df %>% 
  group_by(ID) %>% 
  summarize(obs = n()) %>% 
  filter(obs < 3) %>% 
  .$ID
few_id
hurricane_df <- hurricane_df %>% filter(!(ID %in% few_id)) # remove 3 hurricanes

# check if any missing hours (e.g., 0 directly to 12, missing 6)
issue_id <- hurricane_df %>% 
  group_by(ID) %>% 
  summarize(
    obs = n(),
    obs2 = as.integer(difftime(max(time), min(time), units = "hours"))/6 + 1,
    diff = obs - obs2
  ) %>% 
  filter(abs(diff) > 0.167) %>% # some = 1/6. may due to DST time-shift
  .$ID
issue_id

# no such issue. but identify a new issue:
# several different hurricanes with the same name. (3 such hurricane names)
# e.g.,
# https://en.wikipedia.org/wiki/Hurricane_Alice_(December_1954)
# https://en.wikipedia.org/wiki/Hurricane_Alice_(June_1954)
origin_df %>% 
  filter(ID %in% issue_id) %>% 
  select(ID, Month, time)

# manually correct those data
hurricane_df <- 
  hurricane_df %>% 
  mutate(
    # 2 hurricanes with the name ALICE.1954
    ID = ifelse(ID == "ALICE.1954" & Month == "June", "ALICE.1954(1)", ID),
    ID = ifelse(ID == "ALICE.1954", "ALICE.1954(2)", ID),
    # 4 hurricanes with the name SUBTROP:UNNAMED.1974
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "June", "SUBTROP:UNNAMED.1974(1)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "July", "SUBTROP:UNNAMED.1974(2)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974" & Month == "August", "SUBTROP:UNNAMED.1974(3)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1974", "SUBTROP:UNNAMED.1974(4)", ID),
    # 2 hurricanes with the name SUBTROP:UNNAMED.1976
    ID = ifelse(ID == "SUBTROP:UNNAMED.1976" & Month == "May", "SUBTROP:UNNAMED.1976(1)", ID),
    ID = ifelse(ID == "SUBTROP:UNNAMED.1976", "SUBTROP:UNNAMED.1976(2)", ID)
  )

# check again
issue_id <- hurricane_df %>% 
  group_by(ID) %>% 
  summarize(
    obs = n(),
    obs2 = as.integer(difftime(max(time), min(time), units = "hours"))/6 + 1,
    diff = obs - obs2
  ) %>% 
  filter(abs(diff) > 0.167) %>% 
  .$ID
issue_id # no such problem

summary(hurricane_df) # 21691 observations, 704 hurricanes

diff_df <-
  hurricane_df %>% 
  group_by(ID) %>% 
  mutate(
    # diff between t & t-6
    lat_diff = Latitude - lag(Latitude),
    long_diff = Longitude - lag(Longitude),
    wind_diff = Wind.kt - lag(Wind.kt),
    # time: (t - t0)/6, where t0 is the first observation time.
    # you can change this value (e.g. +1, or -1) as you wish
    time = round(difftime(time, min(time), units = "hours")/6) %>% as.integer
  ) %>% 
  drop_na %>% 
  select(ID, lat_diff, long_diff, wind_diff, time)

summary(diff_df)
```
